name: Build EXE on Windows

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller app.py --noconfirm --onefile --icon=logo.ico

      - name: Upload EXE
        uses: actions/upload-artifact@v3
        with:
          name: ShangjianYinqing-EXE
          path: dist/app.exename: Build EXE with PyInstaller

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --noconsole --icon=logo.ico app.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v3
        with:
          name: shangjian-engine-exe
          path: dist/app.exe
